//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptsGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapturePageTagInfo
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string CapturePageName { get; set; }
        public string TagName { get; set; }
        public string TagId { get; set; }
        public string MarketingListName { get; set; }
        public string MarketingListId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
